name: exerscroll
description: A cross-platform app that blocks selected apps until you earn time by performing exercises.
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.2.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    provider: ^6.1.2
    shared_preferences: ^2.2.3
    permission_handler: ^12.0.1
    camera: ^0.10.5+9
    google_mlkit_pose_detection: ^0.14.0
    fl_chart: ^1.1.1
    intl: ^0.20.2
    uuid: ^4.5.1
    usage_stats: ^1.3.1
    device_info_plus: ^10.1.2
    google_mlkit_commons: ^0.11.0
    flutter_overlay_window: ^0.5.0
    window_manager: ^0.5.1
    workmanager: ^0.8.0
    flutter_local_notifications: ^17.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true
