name: exerscroll
description: A cross-platform app that blocks selected apps until you earn time by performing exercises.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  camera: ^0.10.5+9
  google_mlkit_pose_detection: ^0.10.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
